In [1]:
scores=[85,90,78,92,88]
for i in range(len(scores)):
  print(f'scores[{i}]={scores[i]}')


scores[0]=85
scores[1]=90
scores[2]=78
scores[3]=92
scores[4]=88


In [3]:
scores=[85,90,78,92,88]
for score in scores: print(score)

85
90
78
92
88


In [5]:
scores=[85,90,78,92,88]
for idx, val in enumerate(scores):
  print(f'scores[{idx}]={val}')

scores[0]=85
scores[1]=90
scores[2]=78
scores[3]=92
scores[4]=88


In [7]:
scores=[85,90,78,92,88]
doubled=[x*2 for x in scores]
print(doubled)

[170, 180, 156, 184, 176]


In [18]:
arr=[10,20,30,40]
print(arr)
arr.append(50)
print(arr)

[10, 20, 30, 40]
[10, 20, 30, 40, 50]


In [14]:
arr=[10,20,30,40]
arr.insert(2,55)
print(arr)


[10, 20, 55, 30, 40]


In [15]:
arr=[10,20,30,40]
arr.extend([60,70])
print(arr)


[10, 20, 30, 40, 60, 70]


In [17]:
arr=[10,20,30,40]
new_arr=arr+[80,90]
print(new_arr)

[10, 20, 30, 40, 80, 90]


In [23]:
#Linear Search
def linear_search(arr,target):
  for i in range(len(arr)):
    if arr[i]== target:
      return i
  return -1
arr=[14,3,27,9,41,7,35]
target=41
linear_search(arr,target)



4

In [27]:
# Binary search
def Binary_search(arr, target):
  left =0
  right = len(arr)-1
  while left < right:
    mid = (left+right)//2
    if arr[mid]==target :
      return mid
    elif arr[mid] < target: left = mid+1
    else:
      right = mid-1
  return -1
arr =[10,20,30,40,50,60,70,80]
target =70
idx= Binary_search(arr,target)
print(f"Found at indes {idx}")

Found at indes 6


In [30]:
# Binary search
def Binary_search(arr, target):
  left =0
  right = len(arr)-1
  while left < right:
    mid = (left+right)//2
    if arr[mid]==target :
      return mid
    elif arr[mid] < target: left = mid+1
    else:
      right = mid-1
  return -1
arr =['a','b','c','d','e','f','g']
target ='d'
idx= Binary_search(arr,target)
print(f"Found at indes {idx}")

Found at indes 3


In [43]:
import math

def jump_search(arr,  target):
  n=len(arr)
  step=int(math.sqrt(n))
  prev=0
  while arr[min(step,n)-1]<target:
    prev=step
    step+=int(math.sqrt(n))
    if prev>=n:
      return -1
  while arr[prev]<target:
    prev+=1
    if prev==min(step,n):
      return -1
  if arr[prev]==target:
    return prev
  return -1
arr =[10,20,30,40,50,60,70,80]
target =40
idx= jump_search(arr,target)
print(f"Found at index {idx}")

Found at index 3


In [1]:
arr=[64,34,25,12,22,11,90]
arr.sort()
arr.sort(reverse=True)
s=sorted(arr)
words=["banana","apple","cherry"]
words.sort(key=len)


In [7]:
import numpy as np
zero=np.array(10)
print(zero)
print(type(zero))
print("Dimension:",zero.ndim)
print("memory:",zero.nbytes)
one=np.array([12,24,36,48,60])
print(one)
print(type(one))
print("Dimension:",zero.ndim)
print("memory:",zero.nbytes)


10
<class 'numpy.ndarray'>
Dimension: 0
memory: 8
[12 24 36 48 60]
<class 'numpy.ndarray'>
Dimension: 0
memory: 8


In [9]:
import numpy as np
Zero=np.array(10)
print(Zero)
print(type(Zero))
print("Dimensions :",Zero.ndim)
print("Memory :",Zero.nbytes)
One=np.array([12,24,36,48,60])
print(One)
print(type(One))
print("Dimensions :",One.ndim)
print("Memory :",One.nbytes)
Two=np.array([[12,24,36],[48,60,40]])
print(Two)
print(type(Two))
print("Dimensions :",Two.ndim)
print("Memory :",Two.nbytes)
Multi=np.array([[[12,24,36],[48,60,40]],[[34,34,66],[58,30,50]]])
print(Multi)
print(type(Multi))
print("Dimensions :",Multi.ndim)
print("Memory :",Multi.nbytes)

10
<class 'numpy.ndarray'>
Dimensions : 0
Memory : 8
[12 24 36 48 60]
<class 'numpy.ndarray'>
Dimensions : 1
Memory : 40
[[12 24 36]
 [48 60 40]]
<class 'numpy.ndarray'>
Dimensions : 2
Memory : 48
[[[12 24 36]
  [48 60 40]]

 [[34 34 66]
  [58 30 50]]]
<class 'numpy.ndarray'>
Dimensions : 3
Memory : 96


In [14]:
import numpy as np
a=np.array([1,2,3,4,5])
z=np.zeros(5)
o=np.ones((2,3))
r=np.arange(0,10,2)
l=np.linspace(0,1,5)
rd=np.random.randint(1,100,6)
print(a)
print(z)
print(o)
print(r)
print(l)
print(rd)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[93 48 35 71 99 21]


In [21]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print("Original array (a):", a)
add_ten = a + 10
print("a + 10:            ", add_ten)
multiply_two = a * 2
print("a * 2:             ", multiply_two)
sqrt_a = np.sqrt(a)
print("np.sqrt(a):        ", sqrt_a)
square_a = np.square(a)
print("np.square(a):      ", square_a)
clipped_a = np.clip(a, 2, 4)
print("np.clip(a, 2, 4):  ", clipped_a)
mean_a = np.mean(a)
print("np.mean(a):        ", mean_a)
std_a = np.std(a)
print("np.std(a):         ", std_a)
median_a = np.median(a)
print("np.median(a):      ", median_a)
percentile_75 = np.percentile(a, 75)
print("np.percentile(a,75):", percentile_75)
reshaped_a = a.reshape(5, 1)
print("a.reshape(5,1):\n", reshaped_a)
shape_a = a.shape
print("a.shape:           ", shape_a)
dtype_a = a.dtype
print("a.dtype:           ", dtype_a)
float_a = a.astype(float)
print("a.astype(float):   ", float_a)

Original array (a): [1 2 3 4 5]
a + 10:             [11 12 13 14 15]
a * 2:              [ 2  4  6  8 10]
np.sqrt(a):         [1.         1.41421356 1.73205081 2.         2.23606798]
np.square(a):       [ 1  4  9 16 25]
np.clip(a, 2, 4):   [2 2 3 4 4]
np.mean(a):         3.0
np.std(a):          1.4142135623730951
np.median(a):       3.0
np.percentile(a,75): 4.0
a.reshape(5,1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
a.shape:            (5,)
a.dtype:            int64
a.astype(float):    [1. 2. 3. 4. 5.]


In [27]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        swapped = False
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True
        if not swapped:
            break
    return arr
test_array = [64, 34, 25, 12, 22, 11, 90]
print("Sorted Array:", bubble_sort(test_array))


Sorted Array: [11, 12, 22, 25, 34, 64, 90]


In [29]:
def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        if min_index != i:
            arr[i], arr[min_index] = arr[min_index], arr[i]
    return arr
test_array = [64, 34, 25, 12, 22, 11, 90]
print("Sorted Array:", selection_sort(test_array))


Sorted Array: [11, 12, 22, 25, 34, 64, 90]
